### ISSUE TITLE
Stereo delay compiler error

### ISSUE THREAD

**Issue by grayxr** [hexeguitar/hexefx_audiolib_F32#1]
It looks like there's a couple variables which weren't being defined, lines 171-172 in effect_delaystereo.cpp:

https://github.com/hexeguitar/hexefx_audiolib_F32/blob/3af73206637083d5442636b39986ba479256f7eb/src/effect_delaystereo.cpp#L169-L170

**Comment by hexeguitar** [comment]
These were just for debugging, forgot to remove them. Fixed.
